# -*- coding: utf-8 -*-
"""Patient Readmission Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13r87ItscsO3yZjW0605s4Y18UNHq16Ik
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("/content/diabetic_data.csv")

df.head()

df.tail()

df.info()

df.shape

df.describe()

df.isnull().sum()

df.replace("?", np.nan, inplace=True)
print("\nMissing Values After Replacing '?'")
print(df.isnull().sum())

df.drop(columns=[
    'weight',
    'payer_code',
    'medical_specialty',
    'max_glu_serum',
    'A1Cresult'
], inplace=True)

print("Shape after dropping columns:", df.shape)

for col in df.columns:
    if df[col].dtype == "object":
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

print("\nRemaining Missing Values:")
print(df.isnull().sum())

df["readmitted"] = df["readmitted"].replace({
    "<30": 1,
    ">30": 0,
    "NO": 0
})

print("\nTarget Distribution:")
print(df["readmitted"].value_counts())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col].astype(str))

print("\nEncoding Completed!")

X = df.drop("readmitted", axis=1)
y = df["readmitted"]

print("X Shape :", X.shape)
print("y Shape :", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Data :", X_train.shape)
print("Testing Data :", X_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("\nFeature Scaling Completed!")

!pip install imbalanced-learn xgboost -q

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("Before SMOTE :", y_train.value_counts())

print("\nAfter SMOTE :")
print(y_train_smote.value_counts())

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Logistic Regression
lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_smote, y_train_smote)

# Random Forest
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)
rf.fit(X_train_smote, y_train_smote)

# XGBoost
xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train_smote, y_train_smote)

print("All Models Trained Successfully!")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = {
    "Logistic Regression": lr,
    "Random Forest": rf,
    "XGBoost": xgb
}

for name, model in models.items():

    y_pred = model.predict(X_test)

    print("="*50)
    print(name)

    print("Accuracy :", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall   :", recall_score(y_test, y_pred))
    print("F1 Score :", f1_score(y_test, y_pred))

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

best_model = xgb

ConfusionMatrixDisplay.from_estimator(best_model, X_test, y_test)

plt.title("Confusion Matrix")
plt.show()

from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators':[200,300],
    'max_depth':[4,5,6],
    'learning_rate':[0.05,0.1]
}

grid = GridSearchCV(
    XGBClassifier(
        random_state=42,
        eval_metric='logloss'
    ),
    params,
    cv=3,
    scoring='f1',
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Parameters :", grid.best_params_)

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

# Final XGBoost Model
final_model = XGBClassifier(
    learning_rate=0.1,
    max_depth=6,
    n_estimators=300,
    random_state=42,
    eval_metric='logloss'
)

# Train Model
final_model.fit(X_train_smote, y_train_smote)

# Prediction
y_pred = final_model.predict(X_test)

# Evaluation
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

import pandas as pd
import matplotlib.pyplot as plt

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": final_model.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)

print(importance.head(15))

plt.figure(figsize=(8,6))
plt.barh(importance["Feature"][:15], importance["Importance"][:15])
plt.gca().invert_yaxis()
plt.title("Top 15 Important Features")
plt.show()

sample = X.iloc[[0]]

prediction = final_model.predict(sample)

if prediction[0] == 1:
    print("Patient is likely to be Readmitted")
else:
    print("Patient is NOT likely to be Readmitted")

