# -*- coding: utf-8 -*-
"""Smart Credit Scoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18md6GRhAnD0Zk_8oUV6_fqmFjfHKD0bN

https://www.kaggle.com/competitions/home-credit-default-risk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
print("Libraries Imported Successfully")

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("/content/application_train.csv")

df.head()

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.info()

df.dtypes

df.describe().T

print("Duplicate Rows :", df.duplicated().sum())

missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})
missing.sort_values(
    by="Missing Values",
    ascending=False
).head(20)

df["TARGET"].value_counts()
(df["TARGET"].value_counts(normalize=True)*100)
df.memory_usage(deep=True).sum()/1024**2

plt.figure(figsize=(6,4))
sns.countplot(x='TARGET', data=df)
plt.title("Loan Default Distribution")
plt.xlabel("Target (0 = No Default, 1 = Default)")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='CODE_GENDER', data=df)
plt.title("Gender Distribution")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='NAME_CONTRACT_TYPE', data=df)
plt.title("Loan Contract Type")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['AMT_INCOME_TOTAL'], bins=40, kde=True)
plt.title("Income Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['AMT_CREDIT'], bins=40, kde=True)
plt.title("Credit Amount Distribution")
plt.show()

plt.figure(figsize=(12,8))

corr = df[
[
'TARGET',
'AMT_INCOME_TOTAL',
'AMT_CREDIT',
'AMT_ANNUITY',
'CNT_CHILDREN',
'DAYS_BIRTH',
'DAYS_EMPLOYED'
]
].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")
plt.show()

missing = df.isnull().sum().sort_values(ascending=False)[:20]

plt.figure(figsize=(10,6))
missing.plot(kind='bar')
plt.title("Top 20 Missing Value Columns")
plt.ylabel("Missing Count")
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(8,4))
sns.boxplot(x=df['AMT_INCOME_TOTAL'])
plt.title("Income Outliers")
plt.show()

df["INCOME_CREDIT_RATIO"] = df["AMT_INCOME_TOTAL"] / df["AMT_CREDIT"]
df["ANNUITY_INCOME_RATIO"] = df["AMT_ANNUITY"] / df["AMT_INCOME_TOTAL"]
df["CREDIT_INCOME_RATIO"] = df["AMT_CREDIT"] / df["AMT_INCOME_TOTAL"]
df["EMPLOYMENT_AGE_RATIO"] = abs(df["DAYS_EMPLOYED"]) / abs(df["DAYS_BIRTH"])
df["CREDIT_PER_PERSON"] = df["AMT_CREDIT"] / (df["CNT_FAM_MEMBERS"] + 1)
df["INCOME_PER_PERSON"] = df["AMT_INCOME_TOTAL"] / (df["CNT_FAM_MEMBERS"] + 1)
df["AGE_YEARS"] = abs(df["DAYS_BIRTH"]) / 365
df["YEARS_EMPLOYED"] = abs(df["DAYS_EMPLOYED"]) / 365

new_features = [
    "INCOME_CREDIT_RATIO",
    "ANNUITY_INCOME_RATIO",
    "CREDIT_INCOME_RATIO",
    "EMPLOYMENT_AGE_RATIO",
    "CREDIT_PER_PERSON",
    "INCOME_PER_PERSON",
    "AGE_YEARS",
    "YEARS_EMPLOYED"
]

df[new_features].head()

missing_percent = (df.isnull().sum() / len(df)) * 100
drop_cols = missing_percent[missing_percent > 60].index
print("Columns to Drop:", len(drop_cols))
df.drop(columns=drop_cols, inplace=True)
print("New Shape:", df.shape)

num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include='object').columns
print("Numerical Columns :", len(num_cols))
print("Categorical Columns :", len(cat_cols))

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

print(df.isnull().sum().sum())

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col].astype(str))

X = df.drop(["TARGET"], axis=1)
y = df["TARGET"]

X = X.drop("SK_ID_CURR", axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

from xgboost import XGBClassifier
!pip install catboost
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)
lr_pred = lr.predict(X_test_scaled)
lr_acc = accuracy_score(y_test, lr_pred)
print("Logistic Regression :", round(lr_acc*100,2),"%")

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
dt_acc = accuracy_score(y_test, dt_pred)
print("Decision Tree :", round(dt_acc*100,2),"%")

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)
print("Random Forest :", round(rf_acc*100,2),"%")

et = ExtraTreesClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)
et.fit(X_train, y_train)
et_pred = et.predict(X_test)
et_acc = accuracy_score(y_test, et_pred)
print("Extra Trees :", round(et_acc*100,2),"%")

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42,
    eval_metric="logloss"
)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)
xgb_acc = accuracy_score(y_test, xgb_pred)
print("XGBoost :", round(xgb_acc*100,2),"%")

cat = CatBoostClassifier(
    iterations=300,
    learning_rate=0.05,
    depth=6,
    random_state=42,
    verbose=0
)
cat.fit(X_train, y_train)
cat_pred = cat.predict(X_test)
cat_acc = accuracy_score(y_test, cat_pred)
print("CatBoost :", round(cat_acc*100,2),"%")

import pandas as pd

accuracy = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Extra Trees",
        "XGBoost",
        "CatBoost"
    ],
    "Accuracy": [
        lr_acc*100,
        dt_acc*100,
        rf_acc*100,
        et_acc*100,
        xgb_acc*100,
        cat_acc*100
    ]
})
accuracy = accuracy.sort_values(by="Accuracy", ascending=False)
accuracy

import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.bar(accuracy["Algorithm"], accuracy["Accuracy"])
plt.xticks(rotation=20)
plt.ylabel("Accuracy (%)")
plt.title("Accuracy Comparison of Machine Learning Models")
plt.show()

best_model = xgb

print("Best Model : XGBoost")
print("Accuracy :", round(xgb_acc*100,2),"%")

sample = X.sample(1, random_state=15)
prediction = best_model.predict(sample)[0]
prob = best_model.predict_proba(sample)[0][1]
print("="*50)
print("Home Credit Default Risk Prediction")
print("="*50)
print("Prediction :", prediction)
print("Risk Probability :", round(prob*100,2),"%")
if prediction==0:
    print("Customer is Eligible for Loan")
else:
    print("Customer is Likely to Default")

import joblib
joblib.dump(best_model, 'Smart Credit Scoring.joblib')

